### ISSUE TITLE
Game type translation key is missing

### ISSUE THREAD

**Issue by haykam821** [NucleoidMC/DestroyTheMonument#8]
The previous game type translation key now refers to the nonexistent `destroy_the_monument:destroy_the_monument` game in Plasmid 0.5:

https://github.com/NucleoidMC/DestroyTheMonument/blob/6b9d630edbc44e1dd95f04cdbf5e50c136b2d8e7/src/main/resources/data/destroy_the_monument/lang/en_us.json#L2

**Comment by ShockMicro** [comment]
That's the 1.17 branch, which is apparently the default. 1.18 correctly shows `"gameType.destroy_the_monument.destroy_the_monument"`.

**Comment by haykam821** [comment]
You're right; this was already fixed in #7. However, GitHub Actions doesn't seem to be building the `1.18` branch:

https://github.com/NucleoidMC/DestroyTheMonument/blob/999d4d78f1554d4a410ac0dcb2d2d5e832ce9318/.github/workflows/build.yml#L3-L5
